apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull-secret
  namespace: cell
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"harbor.hasslab.pro":{"username":"admin","password":"Harbor12345","auth":"YWRtaW46SGFyYm9yMTIzNDU="}}}'
