apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cell-frequency
  namespace: cell-frequency
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cell.hasslab.pro
      secretName: cell-frequency-tls
  rules:
    - host: cell.hasslab.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cell-frequency
                port:
                  number: 80
